include: package:lint/analysis_options.yaml

linter:
  rules:
    always_use_package_imports: false

    unused_import: false

    avoid_classes_with_only_static_members: false

    avoid_dynamic_calls: false

    avoid_function_literals_in_foreach_calls: false

    sort_pub_dependencies: false

    avoid_positional_boolean_parameters: false

    join_return_with_assignment: false
