name: store
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.2
  scrollable_positioned_list: ^0.3.8
  pinyin: ^3.3.0
  get: 4.6.6
  flutter_screenutil: 5.9.0
  intl: ^0.19.0 
  extended_image: ^9.1.0
  shared_preferences: 2.2.2
  path_provider:  ^2.1.2
  dio: 5.4.0
  cookie_jar: ^4.0.8
  logger: 2.0.2+1
  permission_handler: ^11.3.1
  flutter_svg: 2.0.9
  cached_network_image: ^3.3.0
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  crypto: ^3.0.3
  flutter_contacts: ^1.1.7+1
  decimal: ^2.3.3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  share_plus: ^10.1.2
  firebase_in_app_messaging: ^0.8.0+5
  flutter_local_notifications: ^17.2.2
  flutter_image_compress: ^2.2.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  in_app_review: ^2.0.9
  open_file: ^3.3.2
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.2.5
  jwt_decoder: ^2.0.1
  http_parser: ^4.0.2
  flutter_smart_dialog: ^4.9.6+1
#  flutter_easyloading: 3.0.5
  shengwang_chat_sdk: ^1.3.2+1

  steel_crypt: ^3.0.0+1
  encrypt: ^5.0.3
  text_scroll: ^0.2.0


dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_test:
    sdk: flutter
  lint: 2.1.2
  build_runner: ^2.4.8
  flutter_gen_runner: 5.3.1

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

flutter:
  uses-material-design: true
  assets:

  # assets start

  # GENERATED CODE - DO NOT MODIFY MANUALLY
  # **************************************************************************
  # Auto generated by https://github.com/fluttercandies/assets_generator
  # **************************************************************************

    - assets/images/
    - assets/json/
    - assets/locales/
    - assets/svg/default/

  # assets end

#  fonts:
#    - family: Prohibition
#      fonts:
#        - asset: assets/fonts/Prohibition-Rough_0.otf
#          style: italic
#
#    - family: NotoSans
#      fonts:
#        - asset: assets/fonts/NotoSans-Light.ttf
#          weight: 300
#        - asset: assets/fonts/NotoSans-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/NotoSans-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/NotoSans-Bold.ttf
#          weight: 700

# dependency_overrides:
#   flutter_inappwebview_ios:
#     git:
#       url: https://github.com/pichillilorenzo/flutter_inappwebview.git
#       ref: master
#       path: flutter_inappwebview_ios