// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Resource {
  const Resource._();

  /// {@macro assets_generator.assetsImagesLoginBgPng.preview}
  static const String assetsImagesLoginBgPng = 'assets/images/login_bg.png';

  /// {@macro assets_generator.assetsImagesNoDataPng.preview}
  static const String assetsImagesNoDataPng = 'assets/images/no_data.png';

  static const String assetsLocalesEnJson = 'assets/locales/en.json';

  static const String assetsLocalesTranslationsXlsx =
      'assets/locales/translations.xlsx';

  static const String assetsLocalesZhCnJson = 'assets/locales/zh-cn.json';

  /// {@macro assets_generator.assetsSvgDefaultChatSvg.preview}
  static const String assetsSvgDefaultChatSvg = 'assets/svg/default/chat.svg';

  /// {@macro assets_generator.assetsSvgDefaultCloseSvg.preview}
  static const String assetsSvgDefaultCloseSvg = 'assets/svg/default/close.svg';

  /// {@macro assets_generator.assetsSvgDefaultEyeOffSvg.preview}
  static const String assetsSvgDefaultEyeOffSvg =
      'assets/svg/default/eye_off.svg';

  /// {@macro assets_generator.assetsSvgDefaultEyeOnSvg.preview}
  static const String assetsSvgDefaultEyeOnSvg =
      'assets/svg/default/eye_on.svg';

  /// {@macro assets_generator.assetsSvgDefaultFindSvg.preview}
  static const String assetsSvgDefaultFindSvg = 'assets/svg/default/find.svg';

  /// {@macro assets_generator.assetsSvgDefaultFriendsSvg.preview}
  static const String assetsSvgDefaultFriendsSvg =
      'assets/svg/default/friends.svg';

  /// {@macro assets_generator.assetsSvgDefaultLogoSvg.preview}
  static const String assetsSvgDefaultLogoSvg = 'assets/svg/default/logo.svg';

  /// {@macro assets_generator.assetsSvgDefaultMeSvg.preview}
  static const String assetsSvgDefaultMeSvg = 'assets/svg/default/me.svg';
}
