// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Resource {
  const Resource._();

  /// {@macro assets_generator.assetsImagesLoginBgPng.preview}
  static const String assetsImagesLoginBgPng = 'assets/images/login_bg.png';

  /// {@macro assets_generator.assetsImagesNoDataPng.preview}
  static const String assetsImagesNoDataPng = 'assets/images/no_data.png';

  static const String assetsJsonCountryCodeJson =
      'assets/json/country_code.json';

  static const String assetsLocalesTranslationsXlsx =
      'assets/locales/translations.xlsx';

  static const String assetsLocalesZhCnJson = 'assets/locales/zh-cn.json';

  /// {@macro assets_generator.assetsSvgDefaultAddSvg.preview}
  static const String assetsSvgDefaultAddSvg = 'assets/svg/default/add.svg';

  /// {@macro assets_generator.assetsSvgDefaultChatSvg.preview}
  static const String assetsSvgDefaultChatSvg = 'assets/svg/default/chat.svg';

  /// {@macro assets_generator.assetsSvgDefaultCloseSvg.preview}
  static const String assetsSvgDefaultCloseSvg = 'assets/svg/default/close.svg';

  /// {@macro assets_generator.assetsSvgDefaultContantSvg.preview}
  static const String assetsSvgDefaultContantSvg =
      'assets/svg/default/contant.svg';

  /// {@macro assets_generator.assetsSvgDefaultCopySvg.preview}
  static const String assetsSvgDefaultCopySvg = 'assets/svg/default/copy.svg';

  /// {@macro assets_generator.assetsSvgDefaultEyeOffSvg.preview}
  static const String assetsSvgDefaultEyeOffSvg =
      'assets/svg/default/eye_off.svg';

  /// {@macro assets_generator.assetsSvgDefaultEyeOnSvg.preview}
  static const String assetsSvgDefaultEyeOnSvg =
      'assets/svg/default/eye_on.svg';

  /// {@macro assets_generator.assetsSvgDefaultFindSvg.preview}
  static const String assetsSvgDefaultFindSvg = 'assets/svg/default/find.svg';

  /// {@macro assets_generator.assetsSvgDefaultGroupAddSvg.preview}
  static const String assetsSvgDefaultGroupAddSvg =
      'assets/svg/default/group_add.svg';

  /// {@macro assets_generator.assetsSvgDefaultLogoSvg.preview}
  static const String assetsSvgDefaultLogoSvg = 'assets/svg/default/logo.svg';

  /// {@macro assets_generator.assetsSvgDefaultMeSvg.preview}
  static const String assetsSvgDefaultMeSvg = 'assets/svg/default/me.svg';

  /// {@macro assets_generator.assetsSvgDefaultNoticeSvg.preview}
  static const String assetsSvgDefaultNoticeSvg =
      'assets/svg/default/notice.svg';

  /// {@macro assets_generator.assetsSvgDefaultPasswordProtectSvg.preview}
  static const String assetsSvgDefaultPasswordProtectSvg =
      'assets/svg/default/password_protect.svg';

  /// {@macro assets_generator.assetsSvgDefaultScanSvg.preview}
  static const String assetsSvgDefaultScanSvg = 'assets/svg/default/scan.svg';

  /// {@macro assets_generator.assetsSvgDefaultShoppingSvg.preview}
  static const String assetsSvgDefaultShoppingSvg =
      'assets/svg/default/shopping.svg';

  /// {@macro assets_generator.assetsSvgDefaultSignSussSvg.preview}
  static const String assetsSvgDefaultSignSussSvg =
      'assets/svg/default/sign_suss.svg';

  /// {@macro assets_generator.assetsSvgDefaultUserAddSvg.preview}
  static const String assetsSvgDefaultUserAddSvg =
      'assets/svg/default/user_add.svg';
}
